//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewArea.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientMemberRelation
    {
        public int IngredientId { get; set; }
        public int MemberId { get; set; }
        public double Amount { get; set; }
        public int MeasurementTypeId { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Member Member { get; set; }
        public virtual MeasurementType MeasurementType { get; set; }
    }
}
