//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewArea.COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeasurementType()
        {
            this.IngredientMemberRelations = new HashSet<IngredientMemberRelation>();
            this.RecipeIngredientRelations = new HashSet<RecipeIngredientRelation>();
        }
    
        public int MeasurementTypeId { get; set; }
        public string MeasurementType1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientMemberRelation> IngredientMemberRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipeIngredientRelation> RecipeIngredientRelations { get; set; }
    }
}
